// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.

using System.Security.Cryptography.X509Certificates;
using Duende.IdentityServer.Models;

namespace Duende.IdentityServer.Hosts.Shared.Configuration;

public static class SamlServiceProviders
{
    // Path to the MvcSaml SP certificate, relative to the host's working directory.
    // Must match the file generated by following README.md in the MvcSaml project.
    private const string SpCertificatePath = "../../clients/src/MvcSaml/saml-sp.pfx";
    private const string SpCertificatePassword = "changeit";

    public static IEnumerable<SamlServiceProvider> Get()
    {
        // Load the SP certificate once. When present, it enables AuthnRequest signature
        // validation and assertion encryption.
        var spCert = LoadSpCertificate();

        return
        [
            new SamlServiceProvider
            {
                EntityId = "https://localhost:44350/Saml2",
                DisplayName = "MvcSaml Sample Client",
                Enabled = true,
                // ACS URL follows the Sustainsys.Saml2 convention: <base>/Saml2/Acs
                AssertionConsumerServiceUrls = [new IndexedEndpoint
                {
                    Location = "https://localhost:44350/Saml2/Acs",
                    Binding = SamlBinding.HttpPost
                }],
                // SLO URL follows the Sustainsys.Saml2 convention: <base>/Saml2/Logout
                SingleLogoutServiceUrls = [new SamlEndpointType
                {
                    Location = "https://localhost:44350/Saml2/Logout",
                    Binding = SamlBinding.HttpRedirect
                }],
                // Sign the assertion (not the response envelope) — the Sustainsys default expectation
                SigningBehavior = SamlSigningBehavior.SignAssertion,
                // When the SP certificate is present, require signed AuthnRequests, register the
                // SP's public key for signature validation, and encrypt assertions with it.
                // The same certificate serves both purposes — signing and encryption.
                RequireSignedAuthnRequests = spCert != null,
                Certificates = spCert != null
                    ? [new ServiceProviderCertificate { Certificate = spCert, Use = KeyUse.Both }]
                    : null,
            }
        ];
    }

    // Returns null if the certificate file has not been generated yet.
    // See README.md in the MvcSaml project for generation instructions.
    private static X509Certificate2? LoadSpCertificate()
    {
        if (!File.Exists(SpCertificatePath))
        {
            return null;
        }

        // For ease during development, we load the public key directly from the SP's certificate file.
        // In a deployed application, you would want to distribute the public key through PKI or
        // another secure channel rather than reading the SP's private key material here.
#pragma warning disable SYSLIB0057
        // Only obsolete in .NET 9+; keeping the older API while we support .NET 8.
        return new X509Certificate2(SpCertificatePath, SpCertificatePassword);
#pragma warning restore SYSLIB0057
    }
}
