// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.


#nullable enable

using System.Diagnostics.CodeAnalysis;
using static Duende.IdentityServer.IdentityServerConstants;

namespace Duende.IdentityServer.Configuration;

/// <summary>
/// Settings for automatic signing key management, including key rotation, propagation, and
/// storage behavior.
/// </summary>
public class KeyManagementOptions
{
    /// <summary>
    /// Gets or sets a value indicating whether automatic key management is enabled. When disabled, signing keys must be configured manually.
    /// </summary>
    /// <remarks>Defaults to <c>true</c>.</remarks>
    public bool Enabled { get; set; } = true;

    /// <summary>
    /// Gets or sets the size in bits of RSA keys generated by automatic key management.
    /// </summary>
    /// <remarks>
    /// Defaults to 2048 bits. Applies to all RSA-based signing algorithms
    /// (<c>RS256</c>, <c>RS384</c>, <c>RS512</c>, <c>PS256</c>, <c>PS384</c>, <c>PS512</c>).
    /// </remarks>
    public int RsaKeySize { get; set; } = 2048;

    /// <summary>
    /// Gets or sets the signing algorithms for which automatic key management will generate and rotate keys.
    /// The first algorithm in the collection is used as the default for clients that do not
    /// specify <c>AllowedIdentityTokenSigningAlgorithms</c>.
    /// </summary>
    /// <remarks>
    /// Defaults to <c>RS256</c> without an X.509 certificate wrapper when no algorithms are
    /// specified. Supported algorithm names are <c>RS256</c>, <c>RS384</c>, <c>RS512</c>,
    /// <c>PS256</c>, <c>PS384</c>, <c>PS512</c>, <c>ES256</c>, <c>ES384</c>, and <c>ES512</c>.
    /// X.509 certificate wrapping is not supported for EC keys.
    /// </remarks>
    public ICollection<SigningAlgorithmOptions> SigningAlgorithms { get; set; } = new List<SigningAlgorithmOptions>();

    internal string DefaultSigningAlgorithm => SigningAlgorithms.First().Name;
    internal IEnumerable<string> AllowedSigningAlgorithmNames => SigningAlgorithms.Select(x => x.Name);

    /// <summary>
    /// Gets or sets the window of time treated as an initialization period when no keys have been created
    /// yet, allowing multiple server instances to synchronize before a key is selected.
    /// </summary>
    /// <remarks>Defaults to 5 minutes.</remarks>
    public TimeSpan InitializationDuration { get; set; } = TimeSpan.FromMinutes(5);

    /// <summary>
    /// Gets or sets the delay between re-loading keys from the store during the initialization period,
    /// giving other server instances time to write their newly created keys.
    /// </summary>
    /// <remarks>Defaults to 5 seconds.</remarks>
    public TimeSpan InitializationSynchronizationDelay { get; set; } = TimeSpan.FromSeconds(5);

    /// <summary>
    /// Gets or sets how long keys are cached from the store during the initialization period.
    /// </summary>
    /// <remarks>
    /// Defaults to 1 minute. A shorter cache duration during initialization ensures that newly
    /// written keys from other nodes are picked up quickly.
    /// </remarks>
    public TimeSpan InitializationKeyCacheDuration { get; set; } = TimeSpan.FromMinutes(1);

    /// <summary>
    /// Gets or sets how long keys are cached from the store during normal operation.
    /// </summary>
    /// <remarks>
    /// Defaults to 24 hours. This value is automatically capped at half of
    /// <see cref="PropagationTime"/> to ensure servers have up-to-date key information before
    /// clients need to refresh their discovery caches.
    /// </remarks>
    public TimeSpan KeyCacheDuration { get; set; } = TimeSpan.FromHours(24);

    /// <summary>
    /// Gets or sets the expected time for new keys to propagate to all server instances and for all clients
    /// to refresh their discovery document cache.
    /// </summary>
    /// <remarks>
    /// Defaults to 14 days. New keys are published in the discovery document for this duration
    /// before they become the active signing key, ensuring clients have time to learn about them.
    /// </remarks>
    public TimeSpan PropagationTime { get; set; } = TimeSpan.FromDays(14);

    /// <summary>
    /// Gets or sets the age at which a key stops being used for signing but remains published in the
    /// discovery document for token validation.
    /// </summary>
    /// <remarks>
    /// Defaults to 90 days. After this interval, a new key takes over signing duties while the
    /// old key remains available for validating previously issued tokens during the
    /// <see cref="RetentionDuration"/>.
    /// </remarks>
    public TimeSpan RotationInterval { get; set; } = TimeSpan.FromDays(90);

    /// <summary>
    /// Gets or sets how long a rotated key remains published in the discovery document after it stops being
    /// used for signing.
    /// </summary>
    /// <remarks>
    /// Defaults to 14 days. This allows resource servers to validate tokens signed with the
    /// old key until those tokens expire.
    /// </remarks>
    public TimeSpan RetentionDuration { get; set; } = TimeSpan.FromDays(14);


    internal TimeSpan KeyRetirementAge => RotationInterval + RetentionDuration;


    /// <summary>
    /// Gets or sets a value indicating whether keys are automatically deleted from the store after they have passed their retention period.
    /// </summary>
    /// <remarks>Defaults to <c>true</c>.</remarks>
    public bool DeleteRetiredKeys { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether stored keys are automatically protected using ASP.NET Core Data Protection.
    /// </summary>
    /// <remarks>
    /// Defaults to <c>true</c>. Disable this only if the underlying storage already provides
    /// encryption at rest.
    /// </remarks>
    public bool DataProtectKeys { get; set; } = true;

    /// <summary>
    /// Gets or sets the file system path where keys are stored when using the default file-based key store.
    /// </summary>
    /// <remarks>
    /// Defaults to a <c>keys</c> directory relative to the application's current working
    /// directory. This setting is ignored when a custom <c>ISigningKeyStore</c> is registered.
    /// </remarks>
    public string KeyPath { get; set; } = Path.Combine(Directory.GetCurrentDirectory(), "keys");

    internal void Validate()
    {
        if (SigningAlgorithms.Count == 0)
        {
            SigningAlgorithms = new[] { new SigningAlgorithmOptions("RS256") };
        }
        else
        {
            var group = SigningAlgorithms.GroupBy(x => x.Name);
            var dups = group.Where(x => x.Count() > 1);
            if (dups.Any())
            {
                var names = dups.Select(x => x.Key).Aggregate((x, y) => $"{x}, {y}");
                throw new Exception($"Duplicate signing algorithms not allowed: '{names}'.");
            }
        }

        var invalid = AllowedSigningAlgorithmNames.Where(x => !SupportedSigningAlgorithms.Contains(x)).ToArray();
        if (invalid.Length > 0)
        {
            var values = invalid.Aggregate((x, y) => $"{x}, {y}");
            throw new Exception($"Invalid signing algorithm(s): '{values}'.");
        }

        var invalidEcKeys = SigningAlgorithms.Where(x => x.IsEcKey && x.UseX509Certificate).ToArray();
        if (invalidEcKeys.Length > 0)
        {
            var values = invalidEcKeys.Select(x => x.Name).Aggregate((x, y) => $"{x}, {y}");
            throw new Exception($"UseX509Certificate not currently supported for EC keys. Signing algorithm(s): '{values}'.");
        }

        if (InitializationDuration < TimeSpan.Zero)
        {
            throw new Exception(nameof(InitializationDuration) + " must be greater than or equal to zero.");
        }

        if (InitializationSynchronizationDelay < TimeSpan.Zero)
        {
            throw new Exception(nameof(InitializationSynchronizationDelay) + " must be greater than or equal to zero.");
        }

        if (InitializationKeyCacheDuration < TimeSpan.Zero)
        {
            throw new Exception(nameof(InitializationKeyCacheDuration) + " must be greater than or equal to zero.");
        }

        if (KeyCacheDuration < TimeSpan.Zero)
        {
            throw new Exception(nameof(KeyCacheDuration) + " must be greater than or equal to zero.");
        }

        if (PropagationTime <= TimeSpan.Zero)
        {
            throw new Exception(nameof(PropagationTime) + " must be greater than zero.");
        }

        if (RotationInterval <= TimeSpan.Zero)
        {
            throw new Exception(nameof(RotationInterval) + " must be greater than zero.");
        }

        if (RetentionDuration <= TimeSpan.Zero)
        {
            throw new Exception(nameof(RetentionDuration) + " must be greater than zero.");
        }

        if (KeyCacheDuration > PropagationTime / 2)
        {
            // we should not cache too long, because we need a server to have latest data
            // to allow clients/apis time to update their caches.
            // todo: error, or just calculate it?
            KeyCacheDuration = PropagationTime / 2;
        }

        if (RotationInterval <= PropagationTime)
        {
            throw new Exception(nameof(RotationInterval) + " must be longer than " + nameof(PropagationTime));
        }
    }
}

/// <summary>
/// Configures a signing algorithm used by automatic key management.
/// </summary>
public class SigningAlgorithmOptions
{
    /// <summary>
    /// Parameterless constructor, required for options binding.
    /// </summary>
    public SigningAlgorithmOptions()
    {

    }

    /// <summary>
    /// Initializes a new instance with the specified algorithm name.
    /// </summary>
    [SetsRequiredMembers]
    public SigningAlgorithmOptions(string name) => Name = name ?? throw new ArgumentNullException(nameof(name));

    /// <summary>
    /// Gets or sets the name of the signing algorithm (e.g., <c>RS256</c>, <c>ES256</c>).
    /// </summary>
    /// <remarks>
    /// Supported values are <c>RS256</c>, <c>RS384</c>, <c>RS512</c>, <c>PS256</c>,
    /// <c>PS384</c>, <c>PS512</c>, <c>ES256</c>, <c>ES384</c>, and <c>ES512</c>.
    /// </remarks>
    public required string Name { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether the generated signing key is wrapped in an X.509 certificate.
    /// </summary>
    /// <remarks>
    /// Defaults to <c>false</c>. X.509 certificate wrapping is not supported for EC keys
    /// (<c>ES256</c>, <c>ES384</c>, <c>ES512</c>). Note that IdentityServer does not validate
    /// the expiration date of X.509 certificates; expired certificates must be replaced manually.
    /// </remarks>
    public bool UseX509Certificate { get; set; }

    internal bool IsRsaKey => Name.StartsWith('R') || Name.StartsWith('P');
    internal bool IsEcKey => Name.StartsWith('E');
}
