// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.


using Duende.IdentityServer.Configuration.Models.DynamicClientRegistration;
using Duende.IdentityServer.Configuration.Validation.DynamicClientRegistration;

namespace Duende.IdentityServer.Configuration.RequestProcessing;

/// <summary>
/// Processes a successfully validated dynamic client registration request by assigning
/// server-generated properties to the client model (such as the client ID and client secret)
/// and persisting the new client via the <see cref="IClientConfigurationStore"/>.
/// </summary>
/// <remarks>
/// Conceptually, the request processor is responsible for setting properties on the
/// <see cref="DynamicClientRegistrationContext.Client"/> model
/// that are generated by the Configuration API itself, rather than supplied by the caller. In
/// contrast, the <see cref="IDynamicClientRegistrationValidator"/>
/// is responsible for checking the validity of the metadata supplied in the registration request
/// and using that metadata to set properties of the client model.
/// <para>
/// The default implementation is <c>DynamicClientRegistrationRequestProcessor</c>, which
/// provides virtual methods for each processing step (e.g., <c>AddClientId</c>,
/// <c>AddClientSecret</c>). To customize processing, derive from
/// <c>DynamicClientRegistrationRequestProcessor</c> and override the relevant step methods
/// rather than implementing this interface from scratch.
/// </para>
/// </remarks>
public interface IDynamicClientRegistrationRequestProcessor
{
    /// <summary>
    /// Processes a valid dynamic client registration request, setting properties of the client
    /// that are not specified in the request (such as the client ID and client secret), and
    /// storing the new client in the <see cref="IClientConfigurationStore"/>.
    /// </summary>
    /// <param name="validatedRequest">
    /// The context for the validated DCR request, including the client model populated by the
    /// validator and the original request metadata.
    /// </param>
    /// <param name="ct">The cancellation token.</param>
    /// <returns>
    /// An <see cref="IDynamicClientRegistrationResponse"/> that either represents the
    /// successfully registered client (including the assigned client ID and secret) or an error.
    /// </returns>
    Task<IDynamicClientRegistrationResponse> ProcessAsync(DynamicClientRegistrationContext validatedRequest, Ct ct);
}
