// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

namespace Duende.UserManagement.Authentication.Passwords;

partial record ValidatedPlainTextPassword
{

    internal static ValidatedPlainTextPassword Load(string value) => new ValidatedPlainTextPassword(value);

}
