// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using Duende.UserManagement;

namespace Duende.UserManagement.Scim.Internal;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<ScimETag, global::System.Int32>))]
partial record ScimETag : IValueOf<ScimETag, global::System.Int32>
{
    // Constructor for controlled creation
    /// <summary>Initializes a new instance of <see cref="ScimETag"/> with the specified value.</summary>
    /// <param name="value">The underlying value.</param>
    private ScimETag(global::System.Int32 value) => Value = value;

    /// <summary>Gets the underlying value of this <see cref="ScimETag"/>.</summary>
    public global::System.Int32 Value { get; }

    /// <summary>Creates a <see cref="ScimETag"/> from the specified string, throwing if the value is invalid.</summary>
    /// <param name="s">The string value to create the <see cref="ScimETag"/> from.</param>
    /// <returns>A new <see cref="ScimETag"/> parsed from <paramref name="s"/>.</returns>
    /// <exception cref="global::System.FormatException">Thrown when <paramref name="s"/> is not a valid value.</exception>
    public static ScimETag Create(string s)
    {
        if (!TryCreate(s, out var result))
        {
            throw new FormatException($"The value '{s}' is not a valid '{nameof(ScimETag)}'.");
        }
        return result;
    }

    /// <summary>Implicitly converts a <c>global::System.Int32</c> to a <see cref="ScimETag"/>.</summary>
    /// <param name="value">The value to convert.</param>
    /// <returns>A new <see cref="ScimETag"/> wrapping <paramref name="value"/>.</returns>

    public static implicit operator ScimETag(global::System.Int32 value)
    {
        return new ScimETag(value);
    }

    /// <inheritdoc />
    public override string ToString() => Value.ToString(null, global::System.Globalization.CultureInfo.InvariantCulture);

    /// <summary>Creates a <see cref="ScimETag"/> from the specified string, or returns <see langword="null"/> if the input is null or empty.</summary>
    /// <param name="input">The string value to parse, or <see langword="null"/>.</param>
    /// <returns>A <see cref="ScimETag"/> if <paramref name="input"/> is non-empty; otherwise <see langword="null"/>.</returns>
    public static ScimETag? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    /// <summary>Loads a <see cref="ScimETag"/> directly from a stored value, bypassing validation. For infrastructure use only.</summary>
    /// <param name="value">The raw stored value.</param>
    /// <returns>A <see cref="ScimETag"/> wrapping <paramref name="value"/>.</returns>
    internal static ScimETag Load(global::System.Int32 value) => new ScimETag(value);
}
