// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System;
using System.Text;

namespace Duende.Storage;

/// <summary>
/// Extension methods for CharSet validation
/// </summary>
internal static class CharSetExtensions
{
    /// <summary>
    /// Defines the set of symbols for the 'Symbols' flag.
    /// </summary>
    private const string SymbolSet = "!@#$%^&*()_+-=[]{}|;:',.<>/?";

    /// <summary>
    /// Gets the combined string of all allowed characters for a given CharSet.
    /// </summary>
    internal static string GetAllowedCharacters(this CharSet charset)
    {
        var sb = new StringBuilder();

        if (charset.HasFlag(CharSet.LowercaseLatin))
        {
            sb.Append("abcdefghijklmnopqrstuvwxyz");
        }
        if (charset.HasFlag(CharSet.UppercaseLatin))
        {
            sb.Append("ABCDEFGHIJKLMNOPQRSTUVWXYZ");
        }
        if (charset.HasFlag(CharSet.Digits))
        {
            sb.Append("0123456789");
        }
        if (charset.HasFlag(CharSet.Symbols))
        {
            sb.Append(SymbolSet);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Checks if a string contains ONLY characters defined by the CharSet.
    /// </summary>
    /// <param name="charset">The charset to validate against.</param>
    /// <param name="input">The string to check.</param>
    /// <returns>True if the string is null, empty, or contains only allowed characters. False otherwise.</returns>
    internal static bool IsMatch(this CharSet charset, string input)
    {
        // An empty or null string contains no *invalid* characters.
        if (string.IsNullOrEmpty(input))
        {
            return true;
        }

        // Cache the flags for quick lookups inside the loop
        bool allowLower = charset.HasFlag(CharSet.LowercaseLatin);
        bool allowUpper = charset.HasFlag(CharSet.UppercaseLatin);
        bool allowDigits = charset.HasFlag(CharSet.Digits);
        bool allowSymbols = charset.HasFlag(CharSet.Symbols);

        foreach (char c in input)
        {
            // We use a series of 'continue' statements.
            // If any condition is met, the character is valid, and we check the next.

            // Using BCL methods is faster than c >= 'a' && c <= 'z'
            if (allowLower && char.IsAsciiLetterLower(c))
            {
                continue;
            }
            if (allowUpper && char.IsAsciiLetterUpper(c))
            {
                continue;
            }
            if (allowDigits && char.IsAsciiDigit(c))
            {
                continue;
            }

            // For symbols, checking against the string is the clearest way
            if (allowSymbols && SymbolSet.Contains(c))
            {
                continue;
            }

            // If we get here, the character 'c' did not match any
            // allowed set, so the string is not a match.
            return false;
        }

        // If the loop finishes, all characters were valid.
        return true;
    }
}
