// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace Duende.UserManagement;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<UserSubjectId, string>))]
partial record UserSubjectId : IStringValue<UserSubjectId>
{
    // Constructor for controlled creation
    private UserSubjectId(string value) => Value = value;

    /// <summary>Gets the underlying string value of this <see cref="UserSubjectId"/>.</summary>
    public string Value { get; }

    /// <summary>Creates a <see cref="UserSubjectId" /> from the specified string value.</summary>
    /// <param name="s">The string value.</param>
    /// <returns>A new <see cref="UserSubjectId" /> instance.</returns>
    /// <exception cref="FormatException">Thrown when <paramref name="s" /> is not a valid <see cref="UserSubjectId" />.</exception>
    public static UserSubjectId Create(string s)
    {
        if (!TryCreate(s, out var result, out var errors))
        {
            throw new FormatException($"The value '{s}' is not a valid UserSubjectId. {string.Join(" ", errors)}");
        }
        return result;
    }

    /// <summary>Tries to create a <see cref="UserSubjectId" /> from the specified string value.</summary>
    /// <param name="s">The string value.</param>
    /// <param name="result">When this method returns <see langword="true" />, contains the created <see cref="UserSubjectId" />.</param>
    /// <returns><see langword="true" /> if the value is valid; otherwise, <see langword="false" />.</returns>
    public static bool TryCreate(string? s, [NotNullWhen(true)] out UserSubjectId? result)
        => TryCreate(s, out result, out _);

    /// <summary>Tries to create a <see cref="UserSubjectId" /> from the specified string value.</summary>
    /// <param name="s">The string value.</param>
    /// <param name="result">When this method returns <see langword="true" />, contains the created <see cref="UserSubjectId" />.</param>
    /// <param name="errors">When this method returns <see langword="false" />, contains the validation errors.</param>
    /// <returns><see langword="true" /> if the value is valid; otherwise, <see langword="false" />.</returns>
    public static bool TryCreate(string? s, [NotNullWhen(true)] out UserSubjectId? result, [NotNullWhen(false)] out IReadOnlyList<string>? errors)
    {
        result = null;
        errors = null;
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["A value is required."];
            return false;
        }

        var validationErrors = new List<string>();
        if (s.Length > MaxLength)
        {
            validationErrors.Add($"Must not exceed {MaxLength} characters.");
        }
        if (validationErrors.Count > 0)
        {
            errors = validationErrors;
            return false;
        }
        result = new UserSubjectId(s);
        return true;
    }

    /// <summary>Implicitly converts a <see cref="string"/> to a <see cref="UserSubjectId"/>.</summary>
    /// <param name="value">The string value to convert.</param>
    /// <returns>A new <see cref="UserSubjectId"/> instance.</returns>
    public static implicit operator UserSubjectId(string value) => Create(value);

    /// <inheritdoc />
    public override string ToString() => Value;

    /// <summary>Creates a new <see cref="UserSubjectId"/> from the specified string value, or returns <see langword="null"/> if the input is null or empty.</summary>
    /// <param name="input">The string value to create the <see cref="UserSubjectId"/> from.</param>
    /// <returns>A new <see cref="UserSubjectId"/> instance, or <see langword="null"/> if <paramref name="input"/> is null or empty.</returns>
    public static UserSubjectId? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    internal static UserSubjectId Load(string value) => new UserSubjectId(value);

}
