// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using Duende.UserManagement;

namespace Duende.UserManagement.Authentication.Internal;

partial record Pbkdf2PseudorandomFunctionName : IValueOf<string>
{

}
