// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.

using System.Buffers.Binary;
using System.Formats.Cbor;
using System.Security.Cryptography;
using Duende.UserManagement;
using Duende.UserManagement.Authentication;
using Duende.UserManagement.Authentication.Passkeys.Internal;

namespace Duende.Platform.UserManagement.Passkeys;

public static class TpmStructuresTests
{
    // The "magic" field in TPMS_ATTEST must equal TPM_GENERATED_VALUE (0xff544347, "ÿTCG")
    // to prove the structure was generated by a genuine TPM.
    // See TPM 2.0 Part 2, section 6.2 (TPM_GENERATED_VALUE).
    private const uint InvalidTpmGeneratedMagic = 0x12345678;

    // TPMS_ATTEST.type identifies the attestation statement kind (e.g., ST_ATTEST_CERTIFY = 0x8017).
    // See TPM 2.0 Part 2, section 10.12.8 (TPMS_ATTEST) and section 6.9 (TPMI_ST_ATTEST).
    private const ushort InvalidAttestationStatementType = 0x9999;

    // TPMT_PUBLIC.type and TPMT_SIGNATURE.sigAlg identify the algorithm (RSA, ECC, etc.).
    // See TPM 2.0 Part 2, section 12.2.4 (TPMT_PUBLIC) and section 11.3.4 (TPMT_SIGNATURE).
    private const ushort UnsupportedAlgorithmId = 0x9999;

    // TPM object attributes are bit flags describing key usage policies (sign, decrypt, fixedTPM, etc.).
    // See TPM 2.0 Part 2, section 8.3 (TPMA_OBJECT).
    private const uint TestObjectAttributes = 0x11223344;
    private const uint AlternateTestObjectAttributes = 0x55667788;

    private const ushort TestRsaKeyBits = 2048;
    private const uint TestRsaExponent = 65537;

    // KDF scheme for ECC parameters. 0x0000 is not a valid algorithm ID but is used here
    // as a null/no-op KDF. See TPM 2.0 Part 2, section 11.2.5 (TPMS_ECC_PARMS).
    private const ushort NullKdf = 0x0000;

    // "Don't care" values used when a test only exercises one specific field and the
    // remaining TPMS_CLOCK_INFO / firmware fields are irrelevant to the assertion.
    // See TPM 2.0 Part 2, section 10.11.1 (TPMS_CLOCK_INFO) and 10.12.8 (TPMS_ATTEST).
    private const ulong FillerClock = 1UL;
    private const uint FillerResetCount = 2U;
    private const uint FillerRestartCount = 3U;
    private const byte FillerSafe = 4;
    private const ulong FillerFirmwareVersion = 5UL;

    private const ulong TestClock = 100UL;
    private const uint TestResetCount = 200U;
    private const uint TestRestartCount = 300U;
    private const byte TestSafe = 1;
    private const ulong TestFirmwareVersion = 500UL;
    private const byte TrailingByte = 0xAA;

    [Fact]
    public static void Parse_tpms_attest_with_valid_data_returns_expected_values()
    {
        var qualifiedSigner = new byte[] { 1, 2 };
        var extraData = new byte[] { 3, 4, 5 };
        var name = new byte[] { 6, 7, 8 };
        var qualifiedName = new byte[] { 9, 10 };
        var clock = TestClock;
        var resetCount = TestResetCount;
        var restartCount = TestRestartCount;
        var safe = TestSafe;
        var firmwareVersion = TestFirmwareVersion;
        var bytes = CreateTpmsAttestBytes(
            TpmConstants.GeneratedValue,
            TpmConstants.StAttestCertify,
            qualifiedSigner,
            extraData,
            clock,
            resetCount,
            restartCount,
            safe,
            firmwareVersion,
            name,
            qualifiedName);

        var result = TpmsAttest.Parse(bytes);

        result.Magic.ShouldBe(TpmConstants.GeneratedValue);
        result.Type.ShouldBe(TpmConstants.StAttestCertify);
        result.QualifiedSigner.ShouldBe(qualifiedSigner);
        result.ExtraData.ShouldBe(extraData);
        result.ClockInfo.Clock.ShouldBe(clock);
        result.ClockInfo.ResetCount.ShouldBe(resetCount);
        result.ClockInfo.RestartCount.ShouldBe(restartCount);
        result.ClockInfo.Safe.ShouldBe(safe);
        result.FirmwareVersion.ShouldBe(firmwareVersion);
        result.Attested.Name.ShouldBe(name);
        result.Attested.QualifiedName.ShouldBe(qualifiedName);
    }

    [Fact]
    public static void Parse_tpms_attest_with_invalid_magic_throws_format_exception()
    {
        var bytes = CreateTpmsAttestBytes(
            InvalidTpmGeneratedMagic,
            TpmConstants.StAttestCertify,
            [1],
            [2],
            FillerClock,
            FillerResetCount,
            FillerRestartCount,
            FillerSafe,
            FillerFirmwareVersion,
            [3],
            [4]);

        _ = Should.Throw<FormatException>(() => TpmsAttest.Parse(bytes));
    }

    [Fact]
    public static void Parse_tpms_attest_with_invalid_type_throws_format_exception()
    {
        var bytes = CreateTpmsAttestBytes(
            TpmConstants.GeneratedValue,
            InvalidAttestationStatementType,
            [1],
            [2],
            FillerClock,
            FillerResetCount,
            FillerRestartCount,
            FillerSafe,
            FillerFirmwareVersion,
            [3],
            [4]);

        _ = Should.Throw<FormatException>(() => TpmsAttest.Parse(bytes));
    }

    [Fact]
    public static void Parse_tpms_attest_with_truncated_data_throws_format_exception()
    {
        var bytes = CreateTpmsAttestBytes(
            TpmConstants.GeneratedValue,
            TpmConstants.StAttestCertify,
            [1],
            [2],
            FillerClock,
            FillerResetCount,
            FillerRestartCount,
            FillerSafe,
            FillerFirmwareVersion,
            [3],
            [4]);
        var truncatedBytes = bytes[..^1];

        _ = Should.Throw<FormatException>(() => TpmsAttest.Parse(truncatedBytes));
    }

    [Fact]
    public static void Parse_tpms_attest_with_trailing_bytes_throws_format_exception()
    {
        var bytes = CreateTpmsAttestBytes(
            TpmConstants.GeneratedValue,
            TpmConstants.StAttestCertify,
            [1],
            [2],
            FillerClock,
            FillerResetCount,
            FillerRestartCount,
            FillerSafe,
            FillerFirmwareVersion,
            [3],
            [4]);
        var trailingData = new[] { TrailingByte };
        var bytesWithTrailingData = Combine(bytes, trailingData);

        _ = Should.Throw<FormatException>(() => TpmsAttest.Parse(bytesWithTrailingData));
    }

    [Fact]
    public static void Parse_tpmt_public_with_valid_Rsa_data_returns_expected_values()
    {
        var authPolicy = new byte[] { 1, 2 };
        var modulus = new byte[] { 3, 4, 5, 6 };
        var objectAttributes = TestObjectAttributes;
        var keyBits = TestRsaKeyBits;
        var exponent = TestRsaExponent;
        var bytes = CreateRsaTpmtPublicBytes(
            TpmConstants.AlgSha256,
            objectAttributes,
            authPolicy,
            TpmConstants.AlgNull,
            TpmConstants.AlgNull,
            keyBits,
            exponent,
            modulus);

        var result = TpmtPublic.Parse(bytes);

        result.Type.ShouldBe(TpmConstants.AlgRsa);
        result.NameAlg.ShouldBe(TpmConstants.AlgSha256);
        result.ObjectAttributes.ShouldBe(objectAttributes);
        result.AuthPolicy.ShouldBe(authPolicy);
        result.Parameters.ShouldBe(CreateRsaParametersBytes(TpmConstants.AlgNull, TpmConstants.AlgNull, keyBits,
            exponent));
        _ = result.RsaParameters.ShouldNotBeNull();
        result.RsaParameters.Symmetric.ShouldBe(TpmConstants.AlgNull);
        result.RsaParameters.Scheme.ShouldBe(TpmConstants.AlgNull);
        result.RsaParameters.KeyBits.ShouldBe(keyBits);
        result.RsaParameters.Exponent.ShouldBe(exponent);
        result.Unique.RsaModulus.ShouldBe(modulus);
        result.Unique.EccX.ShouldBeNull();
        result.Unique.EccY.ShouldBeNull();
        result.EccParameters.ShouldBeNull();
    }

    [Fact]
    public static void Parse_tpmt_public_with_valid_Ecc_data_returns_expected_values()
    {
        var authPolicy = new byte[] { 1, 2 };
        var x = new byte[] { 3, 4, 5 };
        var y = new byte[] { 6, 7, 8 };
        var objectAttributes = AlternateTestObjectAttributes;
        var curveId = TpmConstants.EccCurveNistP256;
        var kdf = NullKdf;
        var bytes = CreateEccTpmtPublicBytes(
            TpmConstants.AlgSha256,
            objectAttributes,
            authPolicy,
            TpmConstants.AlgNull,
            TpmConstants.AlgNull,
            curveId,
            kdf,
            x,
            y);

        var result = TpmtPublic.Parse(bytes);

        result.Type.ShouldBe(TpmConstants.AlgEcc);
        result.NameAlg.ShouldBe(TpmConstants.AlgSha256);
        result.ObjectAttributes.ShouldBe(objectAttributes);
        result.AuthPolicy.ShouldBe(authPolicy);
        result.Parameters.ShouldBe(CreateEccParametersBytes(TpmConstants.AlgNull, TpmConstants.AlgNull, curveId, kdf));
        _ = result.EccParameters.ShouldNotBeNull();
        result.EccParameters.Symmetric.ShouldBe(TpmConstants.AlgNull);
        result.EccParameters.Scheme.ShouldBe(TpmConstants.AlgNull);
        result.EccParameters.CurveId.ShouldBe(curveId);
        result.EccParameters.Kdf.ShouldBe(kdf);
        result.Unique.RsaModulus.ShouldBeNull();
        result.Unique.EccX.ShouldBe(x);
        result.Unique.EccY.ShouldBe(y);
        result.RsaParameters.ShouldBeNull();
    }

    [Fact]
    public static void Parse_tpmt_public_with_unsupported_type_throws_format_exception()
    {
        var bytes = CreateUInt16Bytes(UnsupportedAlgorithmId);

        _ = Should.Throw<FormatException>(() => TpmtPublic.Parse(bytes));
    }

    [Fact]
    public static void Parse_tpmt_public_with_trailing_bytes_throws_format_exception()
    {
        var arbitraryAuthPolicy = new byte[] { 1 };
        var arbitraryModulus = new byte[] { 2, 3, 4, 5 };
        var bytes = CreateRsaTpmtPublicBytes(
            TpmConstants.AlgSha256,
            TestObjectAttributes,
            arbitraryAuthPolicy,
            TpmConstants.AlgNull,
            TpmConstants.AlgNull,
            TestRsaKeyBits,
            TestRsaExponent,
            arbitraryModulus);
        var trailingData = new[] { TrailingByte };
        var bytesWithTrailingData = Combine(bytes, trailingData);

        _ = Should.Throw<FormatException>(() => TpmtPublic.Parse(bytesWithTrailingData));
    }

    [Fact]
    public static void Parse_tpmt_public_with_non_null_rsa_symmetric_throws_format_exception()
    {
        var arbitraryAuthPolicy = new byte[] { 1 };
        var arbitraryModulus = new byte[] { 2, 3, 4, 5 };
        var bytes = CreateRsaTpmtPublicBytes(
            TpmConstants.AlgSha256,
            TestObjectAttributes,
            arbitraryAuthPolicy,
            UnsupportedAlgorithmId,
            TpmConstants.AlgNull,
            TestRsaKeyBits,
            TestRsaExponent,
            arbitraryModulus);

        var exception = Should.Throw<FormatException>(() => TpmtPublic.Parse(bytes));

        ShouldlyExtensions.ShouldContain(exception.Message, "TPMS_RSA_PARMS Symmetric");
        ShouldlyExtensions.ShouldContain(exception.Message, "TPM_ALG_NULL");
    }

    [Fact]
    public static void Parse_tpmt_public_with_non_null_ecc_scheme_throws_format_exception()
    {
        var arbitraryAuthPolicy = new byte[] { 1 };
        var arbitraryX = new byte[] { 2, 3, 4 };
        var arbitraryY = new byte[] { 5, 6, 7 };
        var bytes = CreateEccTpmtPublicBytes(
            TpmConstants.AlgSha256,
            AlternateTestObjectAttributes,
            arbitraryAuthPolicy,
            TpmConstants.AlgNull,
            UnsupportedAlgorithmId,
            TpmConstants.EccCurveNistP256,
            NullKdf,
            arbitraryX,
            arbitraryY);

        var exception = Should.Throw<FormatException>(() => TpmtPublic.Parse(bytes));

        ShouldlyExtensions.ShouldContain(exception.Message, "TPMS_ECC_PARMS Scheme");
        ShouldlyExtensions.ShouldContain(exception.Message, "TPM_ALG_NULL");
    }

    [Fact]
    public static void Compute_name_with_Sha256_name_alg_returns_algorithm_prefix_and_Sha256_digest()
    {
        var objectAttributes = TestObjectAttributes;
        var authPolicy = new byte[] { 1, 2 };
        var modulus = new byte[] { 3, 4, 5, 6 };
        var pubAreaBytes = CreateRsaTpmtPublicBytes(
            TpmConstants.AlgSha256,
            objectAttributes,
            authPolicy,
            TpmConstants.AlgNull,
            TpmConstants.AlgNull,
            TestRsaKeyBits,
            TestRsaExponent,
            modulus);
        var pubArea = TpmtPublic.Parse(pubAreaBytes);
        var expectedDigest = SHA256.HashData(pubAreaBytes);
        var expectedName = new byte[sizeof(ushort) + expectedDigest.Length];
        BinaryPrimitives.WriteUInt16BigEndian(expectedName.AsSpan(), TpmConstants.AlgSha256);
        expectedDigest.CopyTo(expectedName.AsSpan(sizeof(ushort)));

        var result = pubArea.ComputeName(pubAreaBytes);

        result.ShouldBe(expectedName);
    }

    [Fact]
    public static void Validate_extra_data_when_sha256_hash_matches_returns_true()
    {
        var authData = new byte[] { 1, 2, 3 };
        var clientDataHash = new byte[] { 4, 5, 6 };
        var expectedExtraData = SHA256.HashData(WebAuthnCrypto.CombineBytes(authData, clientDataHash));
        var certInfo = CreateTpmsAttest(expectedExtraData, [7]);

        var result = TpmStructures.ValidateExtraData(certInfo, authData, clientDataHash, TpmConstants.AlgSha256);

        result.ShouldBeTrue();
    }

    [Fact]
    public static void Validate_extra_data_when_hash_does_not_match_returns_false()
    {
        var authData = new byte[] { 1, 2, 3 };
        var clientDataHash = new byte[] { 4, 5, 6 };
        var certInfo = CreateTpmsAttest([0xFF, 0xEE, 0xDD], [7]);

        var result = TpmStructures.ValidateExtraData(certInfo, authData, clientDataHash, TpmConstants.AlgSha256);

        result.ShouldBeFalse();
    }

    [Fact]
    public static void Validate_extra_data_when_tpm_hash_algorithm_is_unsupported_returns_false()
    {
        var authData = new byte[] { 1, 2, 3 };
        var clientDataHash = new byte[] { 4, 5, 6 };
        ushort unsupportedTpmHashAlgorithm = 0xFFFF;
        var certInfo = CreateTpmsAttest([0xFF, 0xEE, 0xDD], [7]);

        TpmStructures.ValidateExtraData(certInfo, authData, clientDataHash, unsupportedTpmHashAlgorithm)
            .ShouldBeFalse();
    }

    [Theory]
    [InlineData(CoseAlgorithms.Es256, TpmConstants.AlgSha256)]
    [InlineData(CoseAlgorithms.Es384, TpmConstants.AlgSha384)]
    [InlineData(CoseAlgorithms.Es512, TpmConstants.AlgSha512)]
    [InlineData(CoseAlgorithms.Ps256, TpmConstants.AlgSha256)]
    [InlineData(CoseAlgorithms.Ps384, TpmConstants.AlgSha384)]
    [InlineData(CoseAlgorithms.Ps512, TpmConstants.AlgSha512)]
    [InlineData(CoseAlgorithms.Rs1, TpmConstants.AlgSha1)]
    [InlineData(CoseAlgorithms.Rs256, TpmConstants.AlgSha256)]
    [InlineData(CoseAlgorithms.Rs384, TpmConstants.AlgSha384)]
    [InlineData(CoseAlgorithms.Rs512, TpmConstants.AlgSha512)]
    public static void Get_tpm_hash_algorithm_for_cose_alg_returns_expected_value(
        int coseAlgorithm, ushort expectedTpmHashAlgorithm)
    {
        var result = TpmStructures.GetTpmHashAlgorithmForCoseAlg(coseAlgorithm);

        result.ShouldBe(expectedTpmHashAlgorithm);
    }

    [Fact]
    public static void Get_tpm_hash_algorithm_for_unsupported_cose_alg_returns_null()
    {
        var result = TpmStructures.GetTpmHashAlgorithmForCoseAlg(9999);

        result.ShouldBeNull();
    }

    [Fact]
    public static void Validate_attested_name_when_name_matches_computed_name_returns_true()
    {
        var objectAttributes = TestObjectAttributes;
        var authPolicy = new byte[] { 1, 2 };
        var modulus = new byte[] { 3, 4, 5, 6 };
        var pubAreaBytes = CreateRsaTpmtPublicBytes(
            TpmConstants.AlgSha256,
            objectAttributes,
            authPolicy,
            TpmConstants.AlgNull,
            TpmConstants.AlgNull,
            TestRsaKeyBits,
            TestRsaExponent,
            modulus);
        var pubArea = TpmtPublic.Parse(pubAreaBytes);
        var certInfo = CreateTpmsAttest([7], pubArea.ComputeName(pubAreaBytes));

        var result = TpmStructures.ValidateAttestedName(certInfo, pubArea, pubAreaBytes);

        result.ShouldBeTrue();
    }

    [Fact]
    public static void Validate_attested_name_when_name_does_not_match_computed_name_returns_false()
    {
        var objectAttributes = TestObjectAttributes;
        var authPolicy = new byte[] { 1, 2 };
        var modulus = new byte[] { 3, 4, 5, 6 };
        var mismatchedName = new byte[] { TrailingByte, 0xBB, 0xCC };
        var pubAreaBytes = CreateRsaTpmtPublicBytes(
            TpmConstants.AlgSha256,
            objectAttributes,
            authPolicy,
            TpmConstants.AlgNull,
            TpmConstants.AlgNull,
            TestRsaKeyBits,
            TestRsaExponent,
            modulus);
        var pubArea = TpmtPublic.Parse(pubAreaBytes);
        var certInfo = CreateTpmsAttest([7], mismatchedName);

        var result = TpmStructures.ValidateAttestedName(certInfo, pubArea, pubAreaBytes);

        result.ShouldBeFalse();
    }

    [Fact]
    public static void Validate_public_key_match_for_Rsa_when_modulus_and_exponent_match_returns_true()
    {
        var modulus = new byte[] { 1, 2, 3, 4 };
        var exponent = new byte[] { 0x01, 0x00, 0x01 }; // 65537 in big-endian
        var authPolicy = new byte[] { 5, 6 };
        var pubArea = TpmtPublic.Parse(CreateRsaTpmtPublicBytes(
            TpmConstants.AlgSha256,
            TestObjectAttributes,
            authPolicy,
            TpmConstants.AlgNull,
            TpmConstants.AlgNull,
            TestRsaKeyBits,
            TestRsaExponent,
            modulus));
        var credentialPublicKey = CreateRsaCoseKey(modulus, exponent);

        var result = TpmStructures.ValidatePublicKeyMatch(pubArea, credentialPublicKey);

        result.ShouldBeTrue();
    }

    [Fact]
    public static void Validate_public_key_match_for_Rsa_when_modulus_does_not_match_returns_false()
    {
        var modulus = new byte[] { 1, 2, 3, 4 };
        var authPolicy = new byte[] { 5, 6 };
        var pubArea = TpmtPublic.Parse(CreateRsaTpmtPublicBytes(
            TpmConstants.AlgSha256,
            TestObjectAttributes,
            authPolicy,
            TpmConstants.AlgNull,
            TpmConstants.AlgNull,
            TestRsaKeyBits,
            TestRsaExponent,
            modulus));
        var mismatchedModulus = new byte[] { 1, 2, 3, 5 };
        var exponent = new byte[] { 0x01, 0x00, 0x01 }; // 65537 in big-endian
        var credentialPublicKey = CreateRsaCoseKey(mismatchedModulus, exponent);

        var result = TpmStructures.ValidatePublicKeyMatch(pubArea, credentialPublicKey);

        result.ShouldBeFalse();
    }

    [Fact]
    public static void Validate_public_key_match_for_Ecc_when_coordinates_match_returns_true()
    {
        var x = new byte[] { 1, 2, 3 };
        var y = new byte[] { 4, 5, 6 };
        var authPolicy = new byte[] { 7, 8 };
        var pubArea = TpmtPublic.Parse(CreateEccTpmtPublicBytes(
            TpmConstants.AlgSha256,
            AlternateTestObjectAttributes,
            authPolicy,
            TpmConstants.AlgNull,
            TpmConstants.AlgNull,
            TpmConstants.EccCurveNistP256,
            NullKdf,
            x,
            y));
        var credentialPublicKey = CreateEccCoseKey(CoseConstants.Curves.P256, x, y);

        var result = TpmStructures.ValidatePublicKeyMatch(pubArea, credentialPublicKey);

        result.ShouldBeTrue();
    }

    [Fact]
    public static void Validate_public_key_match_for_Ecc_when_coordinates_do_not_match_returns_false()
    {
        var x = new byte[] { 1, 2, 3 };
        var y = new byte[] { 4, 5, 6 };
        var authPolicy = new byte[] { 7, 8 };
        var pubArea = TpmtPublic.Parse(CreateEccTpmtPublicBytes(
            TpmConstants.AlgSha256,
            AlternateTestObjectAttributes,
            authPolicy,
            TpmConstants.AlgNull,
            TpmConstants.AlgNull,
            TpmConstants.EccCurveNistP256,
            NullKdf,
            x,
            y));
        var mismatchedX = new byte[] { 1, 2, 4 };
        var mismatchedY = new byte[] { 4, 5, 7 };
        var credentialPublicKey = CreateEccCoseKey(CoseConstants.Curves.P256, mismatchedX, mismatchedY);

        var result = TpmStructures.ValidatePublicKeyMatch(pubArea, credentialPublicKey);

        result.ShouldBeFalse();
    }

    [Fact]
    public static void Validate_public_key_match_for_Ecc_when_curve_does_not_match_returns_false()
    {
        var x = new byte[] { 1, 2, 3 };
        var y = new byte[] { 4, 5, 6 };
        var authPolicy = new byte[] { 7, 8 };
        var pubArea = TpmtPublic.Parse(CreateEccTpmtPublicBytes(
            TpmConstants.AlgSha256,
            AlternateTestObjectAttributes,
            authPolicy,
            TpmConstants.AlgNull,
            TpmConstants.AlgNull,
            TpmConstants.EccCurveNistP256,
            NullKdf,
            x,
            y));
        var credentialPublicKey = CreateEccCoseKey(CoseConstants.Curves.P384, x, y);

        var result = TpmStructures.ValidatePublicKeyMatch(pubArea, credentialPublicKey);

        result.ShouldBeFalse();
    }

    private static TpmsAttest CreateTpmsAttest(byte[] extraData, byte[] attestedName) =>
        new(
            TpmConstants.GeneratedValue,
            TpmConstants.StAttestCertify,
            [],
            extraData,
            new TpmsClockInfo(0, 0, 0, 0),
            0,
            new TpmsCertifyInfo(attestedName, []));

    private static CoseKey CreateRsaCoseKey(byte[] modulus, byte[] exponent)
    {
        var writer = new CborWriter();
        writer.WriteStartMap(4);
        writer.WriteInt32(CoseConstants.Labels.KeyType);
        writer.WriteInt32(CoseConstants.KeyTypes.Rsa);
        writer.WriteInt32(CoseConstants.Labels.Algorithm);
        writer.WriteInt32(CoseAlgorithms.Rs256);
        writer.WriteInt32(CoseConstants.Labels.RsaModulus);
        writer.WriteByteString(modulus);
        writer.WriteInt32(CoseConstants.Labels.RsaExponent);
        writer.WriteByteString(exponent);
        writer.WriteEndMap();
        var cbor = writer.Encode();
        _ = CoseKey.TryParse(cbor, out var key);
        return key!;
    }

    private static CoseKey CreateEccCoseKey(int curve, byte[] x, byte[] y)
    {
        var writer = new CborWriter();
        writer.WriteStartMap(5);
        writer.WriteInt32(CoseConstants.Labels.KeyType);
        writer.WriteInt32(CoseConstants.KeyTypes.Ec2);
        writer.WriteInt32(CoseConstants.Labels.Algorithm);
        writer.WriteInt32(CoseAlgorithms.Es256);
        writer.WriteInt32(CoseConstants.Labels.EcCurve);
        writer.WriteInt32(curve);
        writer.WriteInt32(CoseConstants.Labels.EcX);
        writer.WriteByteString(x);
        writer.WriteInt32(CoseConstants.Labels.EcY);
        writer.WriteByteString(y);
        writer.WriteEndMap();
        var cbor = writer.Encode();
        _ = CoseKey.TryParse(cbor, out var key);
        return key!;
    }

    private static byte[] CreateTpmsAttestBytes(
        uint magic,
        ushort type,
        byte[] qualifiedSigner,
        byte[] extraData,
        ulong clock,
        uint resetCount,
        uint restartCount,
        byte safe,
        ulong firmwareVersion,
        byte[] name,
        byte[] qualifiedName)
    {
        var buffer = new List<byte>();
        AddUInt32(buffer, magic);
        AddUInt16(buffer, type);
        AddTpm2B(buffer, qualifiedSigner);
        AddTpm2B(buffer, extraData);
        AddUInt64(buffer, clock);
        AddUInt32(buffer, resetCount);
        AddUInt32(buffer, restartCount);
        buffer.Add(safe);
        AddUInt64(buffer, firmwareVersion);
        AddTpm2B(buffer, name);
        AddTpm2B(buffer, qualifiedName);
        return [.. buffer];
    }

    private static byte[] CreateRsaTpmtPublicBytes(
        ushort nameAlg,
        uint objectAttributes,
        byte[] authPolicy,
        ushort symmetric,
        ushort scheme,
        ushort keyBits,
        uint exponent,
        byte[] modulus)
    {
        var buffer = new List<byte>();
        AddUInt16(buffer, TpmConstants.AlgRsa);
        AddUInt16(buffer, nameAlg);
        AddUInt32(buffer, objectAttributes);
        AddTpm2B(buffer, authPolicy);
        AddBytes(buffer, CreateRsaParametersBytes(symmetric, scheme, keyBits, exponent));
        AddTpm2B(buffer, modulus);
        return [.. buffer];
    }

    private static byte[] CreateEccTpmtPublicBytes(
        ushort nameAlg,
        uint objectAttributes,
        byte[] authPolicy,
        ushort symmetric,
        ushort scheme,
        ushort curveId,
        ushort kdf,
        byte[] x,
        byte[] y)
    {
        var buffer = new List<byte>();
        AddUInt16(buffer, TpmConstants.AlgEcc);
        AddUInt16(buffer, nameAlg);
        AddUInt32(buffer, objectAttributes);
        AddTpm2B(buffer, authPolicy);
        AddBytes(buffer, CreateEccParametersBytes(symmetric, scheme, curveId, kdf));
        AddTpm2B(buffer, x);
        AddTpm2B(buffer, y);
        return [.. buffer];
    }

    private static byte[] CreateRsaParametersBytes(ushort symmetric, ushort scheme, ushort keyBits, uint exponent)
    {
        var buffer = new List<byte>();
        AddUInt16(buffer, symmetric);
        AddUInt16(buffer, scheme);
        AddUInt16(buffer, keyBits);
        AddUInt32(buffer, exponent);
        return [.. buffer];
    }

    private static byte[] CreateEccParametersBytes(ushort symmetric, ushort scheme, ushort curveId, ushort kdf)
    {
        var buffer = new List<byte>();
        AddUInt16(buffer, symmetric);
        AddUInt16(buffer, scheme);
        AddUInt16(buffer, curveId);
        AddUInt16(buffer, kdf);
        return [.. buffer];
    }

    private static byte[] CreateUInt16Bytes(ushort value)
    {
        var bytes = new byte[sizeof(ushort)];
        BinaryPrimitives.WriteUInt16BigEndian(bytes, value);
        return bytes;
    }

    private static byte[] Combine(byte[] first, byte[] second)
    {
        var combined = new byte[first.Length + second.Length];
        first.CopyTo(combined, 0);
        second.CopyTo(combined, first.Length);
        return combined;
    }

    private static void AddTpm2B(List<byte> buffer, byte[] value)
    {
        AddUInt16(buffer, (ushort)value.Length);
        AddBytes(buffer, value);
    }

    private static void AddUInt16(List<byte> buffer, ushort value)
    {
        var bytes = new byte[sizeof(ushort)];
        BinaryPrimitives.WriteUInt16BigEndian(bytes, value);
        AddBytes(buffer, bytes);
    }

    private static void AddUInt32(List<byte> buffer, uint value)
    {
        var bytes = new byte[sizeof(uint)];
        BinaryPrimitives.WriteUInt32BigEndian(bytes, value);
        AddBytes(buffer, bytes);
    }

    private static void AddUInt64(List<byte> buffer, ulong value)
    {
        var bytes = new byte[sizeof(ulong)];
        BinaryPrimitives.WriteUInt64BigEndian(bytes, value);
        AddBytes(buffer, bytes);
    }

    private static void AddBytes(List<byte> buffer, byte[] bytes) => buffer.AddRange(bytes);
}
