// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Collections.Generic;
using Duende.UserManagement;
using System.Diagnostics.CodeAnalysis;

namespace Duende.UserManagement.Membership;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<GroupId, string>))]
partial record GroupId : IStringValue<GroupId>
{
    // Constructor for controlled creation
    private GroupId(string value) => Value = value;

    /// <summary>Gets the underlying string value of this <see cref="GroupId"/>.</summary>
    public string Value { get; }

    /// <summary>Creates a <see cref="GroupId" /> from the specified string value.</summary>
    /// <param name="s">The string value.</param>
    /// <returns>A new <see cref="GroupId" /> instance.</returns>
    /// <exception cref="FormatException">Thrown when <paramref name="s" /> is not a valid <see cref="GroupId" />.</exception>
    public static GroupId Create(string s)
    {
        if (!TryCreate(s, out var result, out var errors))
        {
            throw new FormatException($"The value '{s}' is not a valid GroupId. {string.Join(" ", errors)}");
        }
        return result;
    }

    /// <summary>Tries to create a <see cref="GroupId" /> from the specified string value.</summary>
    /// <param name="s">The string value.</param>
    /// <param name="result">When this method returns <see langword="true" />, contains the created <see cref="GroupId" />.</param>
    /// <returns><see langword="true" /> if the value is valid; otherwise, <see langword="false" />.</returns>
    public static bool TryCreate(string? s, [NotNullWhen(true)] out GroupId? result)
        => TryCreate(s, out result, out _);

    /// <summary>Tries to create a <see cref="GroupId" /> from the specified string value.</summary>
    /// <param name="s">The string value.</param>
    /// <param name="result">When this method returns <see langword="true" />, contains the created <see cref="GroupId" />.</param>
    /// <param name="errors">When this method returns <see langword="false" />, contains the validation errors.</param>
    /// <returns><see langword="true" /> if the value is valid; otherwise, <see langword="false" />.</returns>
    public static bool TryCreate(string? s, [NotNullWhen(true)] out GroupId? result, [NotNullWhen(false)] out IReadOnlyList<string>? errors)
    {
        result = null;
        errors = null;
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["A value is required."];
            return false;
        }

        var validationErrors = new List<string>();
        if (s.Length > MaxLength)
        {
            validationErrors.Add($"Must not exceed {MaxLength} characters.");
        }
        if (!Regex().IsMatch(s))
        {
            validationErrors.Add("Must match the required pattern.");
        }
        if (validationErrors.Count > 0)
        {
            errors = validationErrors;
            return false;
        }
        result = new GroupId(s);
        return true;
    }

    /// <summary>Implicitly converts a <see cref="string"/> to a <see cref="GroupId"/>.</summary>
    /// <param name="value">The string value to convert.</param>
    /// <returns>A new <see cref="GroupId"/> instance.</returns>
    public static implicit operator GroupId(string value) => Create(value);

    /// <inheritdoc />
    public override string ToString() => Value;

    /// <summary>Creates a new <see cref="GroupId"/> from the specified string value, or returns <see langword="null"/> if the input is null or empty.</summary>
    /// <param name="input">The string value to create the <see cref="GroupId"/> from.</param>
    /// <returns>A new <see cref="GroupId"/> instance, or <see langword="null"/> if <paramref name="input"/> is null or empty.</returns>
    public static GroupId? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    internal static GroupId Load(string value) => new GroupId(value);

}
