// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.


using Duende.IdentityServer.Configuration.Models.DynamicClientRegistration;
using Duende.IdentityServer.Configuration.RequestProcessing;

namespace Duende.IdentityServer.Configuration.Validation.DynamicClientRegistration;

/// <summary>
/// Validates a dynamic client registration request and uses the supplied metadata to populate
/// the <see cref="DynamicClientRegistrationContext.Client"/> model. This interface is invoked
/// by the DCR pipeline after the HTTP request has been parsed and before the request processor
/// assigns server-generated properties such as the client ID and secret.
/// </summary>
/// <remarks>
/// Conceptually, the validator is responsible for checking the validity of the metadata
/// supplied in the registration request and translating that metadata into properties on the
/// <see cref="DynamicClientRegistrationContext.Client"/> model. In contrast, the
/// <see cref="IDynamicClientRegistrationRequestProcessor"/> is responsible
/// for setting properties that are generated by the Configuration API itself (e.g., client ID,
/// client secret) and for persisting the finished client.
/// <para>
/// The default implementation is <c>DynamicClientRegistrationValidator</c>, which runs a
/// series of virtual validation steps (e.g., <c>SetGrantTypesAsync</c>,
/// <c>SetRedirectUrisAsync</c>, <c>SetScopesAsync</c>). To customize validation, derive from
/// <c>DynamicClientRegistrationValidator</c> and override the relevant step methods rather
/// than implementing this interface from scratch.
/// </para>
/// </remarks>
public interface IDynamicClientRegistrationValidator
{
    /// <summary>
    /// Validates a dynamic client registration request and populates the client model in the
    /// provided context.
    /// </summary>
    /// <param name="context">
    /// Contextual information about the DCR request, including the raw request metadata, the
    /// client model being built, and the authenticated caller.
    /// </param>
    /// <param name="ct">The cancellation token.</param>
    /// <returns>
    /// A task that returns an <see cref="IDynamicClientRegistrationValidationResult"/>, which
    /// either indicates success (allowing processing to continue) or failure (with an error
    /// code and description to return to the caller).
    /// </returns>
    Task<IDynamicClientRegistrationValidationResult> ValidateAsync(DynamicClientRegistrationContext context, Ct ct);
}
