// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Collections.Generic;
using Duende.IdentityServer;
using System.Diagnostics.CodeAnalysis;

namespace Duende.IdentityServer.Admin;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<DataVersion, global::System.Int32>))]
partial record DataVersion : IValueOf<DataVersion, global::System.Int32>
{
    // Constructor for controlled creation
    /// <summary>Initializes a new instance of <see cref="DataVersion"/> with the specified value.</summary>
    /// <param name="value">The underlying value.</param>
    private DataVersion(global::System.Int32 value) => Value = value;

    /// <summary>Gets the underlying value of this <see cref="DataVersion"/>.</summary>
    public global::System.Int32 Value { get; }

    /// <summary>Creates a <see cref="DataVersion"/> from the specified string, throwing if the value is invalid.</summary>
    /// <param name="s">The string value to create the <see cref="DataVersion"/> from.</param>
    /// <returns>A new <see cref="DataVersion"/> parsed from <paramref name="s"/>.</returns>
    /// <exception cref="global::System.FormatException">Thrown when <paramref name="s"/> is not a valid value.</exception>
    public static DataVersion Create(string s)
    {
        if (!TryCreate(s, out var result, out var errors))
        {
            throw new FormatException($"The value '{s}' is not a valid '{nameof(DataVersion)}'. {string.Join(" ", errors)}");
        }
        return result;
    }

    /// <summary>Tries to create a <see cref="DataVersion"/> from the specified string.</summary>
    /// <param name="s">The string value to parse.</param>
    /// <param name="result">When this method returns <see langword="true"/>, contains the created <see cref="DataVersion"/>; otherwise <see langword="null"/>.</param>
    /// <returns><see langword="true"/> if <paramref name="s"/> is a valid value; otherwise <see langword="false"/>.</returns>
    public static bool TryCreate(string? s, [NotNullWhen(true)] out DataVersion? result)
        => TryCreate(s, out result, out _);

    /// <summary>Tries to create a <see cref="DataVersion"/> from the specified string, returning validation errors on failure.</summary>
    /// <param name="s">The string value to parse.</param>
    /// <param name="result">When this method returns <see langword="true"/>, contains the created <see cref="DataVersion"/>; otherwise <see langword="null"/>.</param>
    /// <param name="errors">When this method returns <see langword="false"/>, contains the validation error messages; otherwise <see langword="null"/>.</param>
    /// <returns><see langword="true"/> if <paramref name="s"/> is a valid value; otherwise <see langword="false"/>.</returns>
    public static bool TryCreate(string? s, [NotNullWhen(true)] out DataVersion? result, [NotNullWhen(false)] out IReadOnlyList<string>? errors)
    {
        result = null;
        errors = null;
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["A value is required."];
            return false;
        }

        if (global::System.Int32.TryParse(s, global::System.Globalization.CultureInfo.InvariantCulture, out var value))
        {
            var instance = new DataVersion(value);
            result = instance;
            return true;
        }

        errors = ["The value could not be parsed."];
        return false;
    }

    /// <summary>Implicitly converts a <c>global::System.Int32</c> to a <see cref="DataVersion"/>.</summary>
    /// <param name="value">The value to convert.</param>
    /// <returns>A new <see cref="DataVersion"/> wrapping <paramref name="value"/>.</returns>
    public static implicit operator DataVersion(global::System.Int32 value)
    {
        return new DataVersion(value);
    }

    /// <inheritdoc />
    public override string ToString() => Value.ToString(null, global::System.Globalization.CultureInfo.InvariantCulture);

    /// <summary>Creates a <see cref="DataVersion"/> from the specified string, or returns <see langword="null"/> if the input is null or empty.</summary>
    /// <param name="input">The string value to parse, or <see langword="null"/>.</param>
    /// <returns>A <see cref="DataVersion"/> if <paramref name="input"/> is non-empty; otherwise <see langword="null"/>.</returns>
    public static DataVersion? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    /// <summary>Loads a <see cref="DataVersion"/> directly from a stored value, bypassing validation. For infrastructure use only.</summary>
    /// <param name="value">The raw stored value.</param>
    /// <returns>A <see cref="DataVersion"/> wrapping <paramref name="value"/>.</returns>
    internal static DataVersion Load(global::System.Int32 value) => new DataVersion(value);
}
