// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Diagnostics.CodeAnalysis;

namespace Duende.UserManagement;

/// <summary>
/// Provides type-safe access to the underlying value of a value object.
/// </summary>
/// <typeparam name="T">The type of the underlying value.</typeparam>
internal interface IValueOf<T>
{
    /// <summary>
    /// Gets the underlying value.
    /// </summary>
    T Value { get; }
}

/// <summary>
/// Provides type-safe access to the underlying value of a value object,
/// along with creation capabilities.
/// </summary>
/// <typeparam name="TSelf">The value object type itself.</typeparam>
/// <typeparam name="T">The type of the underlying value.</typeparam>
internal interface IValueOf<TSelf, T> : IValueOf<T> where TSelf : IValueOf<TSelf, T>
{
    /// <summary>
    /// Creates a value object from a string representation.
    /// </summary>
    static abstract TSelf Create(string s);

    /// <summary>
    /// Tries to create a value object from a string representation.
    /// </summary>
    static abstract bool TryCreate(string? s, [NotNullWhen(true)] out TSelf? result);
}

internal interface IStringValue<TSelf> : IValueOf<TSelf, string> where TSelf : IStringValue<TSelf>
{
}
