// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System;
using System.ComponentModel;
using System.Globalization;

namespace Duende.MultiSpace;

/// <summary>
/// Generic type converter for value objects.
/// Enables ASP.NET Core model binding and IConfiguration support.
/// </summary>
internal class ValueOfTypeConverter<TValue, TType> : TypeConverter where TValue : IValueOf<TValue, TType>
{
    public override bool CanConvertFrom(ITypeDescriptorContext? context, Type sourceType)
    {
        return sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);
    }

    public override object? ConvertFrom(ITypeDescriptorContext? context, CultureInfo? culture, object value)
    {
        if (value is string stringValue)
        {
            if (TValue.TryCreate(stringValue, out var result))
            {
                return result;
            }
            throw new FormatException($"'{stringValue}' is not a valid {typeof(TValue).Name}.");
        }
        return base.ConvertFrom(context, culture!, value);
    }

    public override bool CanConvertTo(ITypeDescriptorContext? context, Type? destinationType)
    {
        return destinationType == typeof(string) || base.CanConvertTo(context, destinationType);
    }

    public override object? ConvertTo(ITypeDescriptorContext? context, CultureInfo? culture, object? value, Type destinationType)
    {
        if (destinationType == typeof(string) && value is TValue typedValue)
        {
            return (typedValue.Value is IFormattable formattable)
                ? formattable.ToString(null, CultureInfo.InvariantCulture)
                : typedValue.Value?.ToString();
        }
        return base.ConvertTo(context, culture, value, destinationType);
    }
}
