name: "templates-ci"

on:
  push:
    branches:
    - main
    paths: 
      - 'templates/**'
  pull_request:
    branches:
    - main
    paths: 
      - 'templates/**'

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup dotnet (main)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - run: dotnet --info
    
    - if: (matrix.runs-on == 'windows-latest') && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
      env:
        SignClientSecret: ${{ secrets.SIGNCLIENTSECRET }}
      run: |
        ./build.ps1
        dotnet nuget push .\artifacts\*.nupkg -s https://www.myget.org/F/duende_identityserver/api/v2/package -k ${{ secrets.MYGET }}
