// <auto-generated by="ValueObjectsGenerator"/>
// Copyright (c) Duende Software. All rights reserved.
// See LICENSE in the project root for license information.
#nullable enable

using System.Collections.Generic;
using Duende.Storage;
using System.Diagnostics.CodeAnalysis;

namespace Duende.Storage.EntityAttributeValue;

[System.ComponentModel.TypeConverter(typeof(ValueOfTypeConverter<AttributeCode, string>))]
partial record AttributeCode : IStringValue<AttributeCode>
{
    // Constructor for controlled creation
    private AttributeCode(string value) => Value = value;

    /// <summary>Gets the underlying string value of this <see cref="AttributeCode"/>.</summary>
    public string Value { get; }

    /// <summary>Creates a <see cref="AttributeCode" /> from the specified string value.</summary>
    /// <param name="s">The string value.</param>
    /// <returns>A new <see cref="AttributeCode" /> instance.</returns>
    /// <exception cref="FormatException">Thrown when <paramref name="s" /> is not a valid <see cref="AttributeCode" />.</exception>
    public static AttributeCode Create(string s)
    {
        if (!TryCreate(s, out var result, out var errors))
        {
            throw new FormatException($"The value '{s}' is not a valid AttributeCode. {string.Join(" ", errors)}");
        }
        return result;
    }

    /// <summary>Tries to create a <see cref="AttributeCode" /> from the specified string value.</summary>
    /// <param name="s">The string value.</param>
    /// <param name="result">When this method returns <see langword="true" />, contains the created <see cref="AttributeCode" />.</param>
    /// <returns><see langword="true" /> if the value is valid; otherwise, <see langword="false" />.</returns>
    public static bool TryCreate(string? s, [NotNullWhen(true)] out AttributeCode? result)
        => TryCreate(s, out result, out _);

    /// <summary>Tries to create a <see cref="AttributeCode" /> from the specified string value.</summary>
    /// <param name="s">The string value.</param>
    /// <param name="result">When this method returns <see langword="true" />, contains the created <see cref="AttributeCode" />.</param>
    /// <param name="errors">When this method returns <see langword="false" />, contains the validation errors.</param>
    /// <returns><see langword="true" /> if the value is valid; otherwise, <see langword="false" />.</returns>
    public static bool TryCreate(string? s, [NotNullWhen(true)] out AttributeCode? result, [NotNullWhen(false)] out IReadOnlyList<string>? errors)
    {
        result = null;
        errors = null;
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["A value is required."];
            return false;
        }

        s = Normalize(s);
        if (string.IsNullOrWhiteSpace(s))
        {
            errors = ["Value is empty after normalization."];
            return false;
        }
        var validationErrors = new List<string>();
        if (s.Length > MaxLength)
        {
            validationErrors.Add($"Must not exceed {MaxLength} characters.");
        }
        if (!TryValidate(s, out var tryValidateErrors))
        {
            if (tryValidateErrors is { Count: > 0 })
            {
                validationErrors.AddRange(tryValidateErrors);
            }
            else
            {
                validationErrors.Add($"The value '{s}' is not valid.");
            }
        }
        if (validationErrors.Count > 0)
        {
            errors = validationErrors;
            return false;
        }
        result = new AttributeCode(s);
        return true;
    }

    /// <summary>Implicitly converts a <see cref="string"/> to a <see cref="AttributeCode"/>.</summary>
    /// <param name="value">The string value to convert.</param>
    /// <returns>A new <see cref="AttributeCode"/> instance.</returns>
    public static implicit operator AttributeCode(string value) => Create(value);

    /// <inheritdoc />
    public override string ToString() => Value;

    /// <summary>Creates a new <see cref="AttributeCode"/> from the specified string value, or returns <see langword="null"/> if the input is null or empty.</summary>
    /// <param name="input">The string value to create the <see cref="AttributeCode"/> from.</param>
    /// <returns>A new <see cref="AttributeCode"/> instance, or <see langword="null"/> if <paramref name="input"/> is null or empty.</returns>
    public static AttributeCode? CreateOrDefault(string? input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return null;
        }

        return Create(input);
    }

    internal static AttributeCode Load(string value) => new AttributeCode(value);

    /// <inheritdoc />
    public virtual bool Equals(AttributeCode? other) =>
        other is not null && Comparer.Equals(Value, other.Value);

    /// <inheritdoc />
    public override int GetHashCode() =>
        Value is null ? 0 : Comparer.GetHashCode(Value);

}
